Resources:
  Bucket: 
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-policy.html
  BucletPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref Bucket
      PolicyDocument:
         Version: 2012-10-17
         Statement:
         - Action:
           - 's3:GetObject'
           - 's3:GetObjectVersion'
           Effect: Allow
           Principal: '*'
           Resource: !Join
           - ''
           - - 'arn:aws:s3:::'
             - !Ref Bucket
             - /*