Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "Key Pair for EC2 instance"

  # Get Latest AMI ID In the region for Amazon Linux
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
    Description: "AMI Used for the EC2 Instance"

Resources:
  EC2EINS:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      ImageId: !Ref LatestAmiId
      Tags:
      - Key: Name 
        Value: "EC2_EINS"

  EC2ZWEI:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      InstanceType: t2.micro
      ImageId: !Ref LatestAmiId
      Tags:
      - Key: Name 
        Value: "EC2_ZWEI"

Outputs:
  EC2EINSOUTPUT:
    Description: Display EC2EINS Instance ID
    Value:  !Ref EC2EINS

  EC2ZWEIOUTPUT:
    Description: Display EC2ZWEI Instance ID
    Value:  !Ref EC2ZWEI